<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "consentmanager_v2"
 *
 * Auto generated by Extension Builder 2021-07-29
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Consent Manager',
    'description' => 'Consent Manager is a GDPR / CCPA consent management solution (SaaS, Software as a Service). In simple words a “cookie banner”. This tool allows to ask website visitors for consent and/or enable opt-out from data processing, cookies, sale of personal information and so on. This helps our clients to fulfil their legal requirements under GDPR, CCPA and other legislations.',
    'category' => 'module',
    'author' => 'consentmanager AB',
    'author_email' => 'info@consentmanager.net',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.3.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
